import { categories, services, getProvider, getService } from './data/services.js';
import { copy } from './data/translations.js';
import { icon } from './components/icons.js';

const app = document.querySelector('#app');
const state = { language: localStorage.getItem('gigs-language') || 'en', query: '', category: 'all', booking: null };
const t = (key) => copy[state.language][key] || copy.en[key] || key;
const route = () => location.hash.slice(1) || '/';
const navigate = (path) => { location.hash = path; window.scrollTo({ top: 0, behavior: 'smooth' }); };
const providerCard = (provider, compact = false) => `<article class="provider-card ${compact ? 'compact' : ''}"><div class="avatar">${provider.initials}</div><div class="provider-copy"><div class="provider-name-line"><strong>${provider.name}</strong><span class="verified" title="${t('verified')}">${icon('check', 14)}</span></div><span>${provider.skill}</span><div class="provider-meta"><span>★ ${provider.rating} (${provider.reviews})</span><span>${provider.experience}</span></div></div>${compact ? '' : `<button class="text-button" data-route="/provider/${provider.id}">${t('viewProfile')} ${icon('chevron', 16)}</button>`}</article>`;
const serviceCard = (service) => { const provider = getProvider(service.providerId); return `<article class="service-card"><div class="service-icon">${icon(service.category)}</div><div class="service-card-content"><p class="eyebrow">${categories.find(c => c.id === service.category).name}</p><h3>${service.title}</h3><p>${service.description}</p><div class="card-footer"><span>${provider.name}</span><button class="round-button" aria-label="View ${service.title}" data-route="/service/${service.id}">${icon('arrow', 18)}</button></div></div></article>`; };
const header = () => `<header class="site-header"><a href="#/" class="brand" aria-label="GIGS home"><span class="brand-mark">G</span><span>GIGS</span></a><nav aria-label="Main navigation"><a href="#/" class="active">${t('navHome')}</a><a href="#/" aria-label="${t('navBookings')}">${t('navBookings')}</a></nav><label class="language-select"><span class="sr-only">${t('language')}</span><select id="language" aria-label="${t('language')}"><option value="en" ${state.language === 'en' ? 'selected' : ''}>English</option><option value="hi" ${state.language === 'hi' ? 'selected' : ''}>हिन्दी</option></select></label></header>`;
const layout = (content) => `${header()}<main>${content}</main><footer><div class="footer-brand"><span class="brand-mark">G</span> GIGS</div><span>Cooperative services, close to home.</span></footer>`;

function home() {
  const visible = services.filter(s => (state.category === 'all' || s.category === state.category) && `${s.title} ${s.description}`.toLowerCase().includes(state.query.toLowerCase()));
  return layout(`<section class="hero"><div class="hero-content"><p class="eyebrow">${t('heroEyebrow')}</p><h1>${t('heroTitle')}</h1><p class="hero-text">${t('heroText')}</p><div class="search-box">${icon('search', 22)}<input id="service-search" value="${state.query}" placeholder="${t('search')}" aria-label="${t('search')}" /></div></div><div class="hero-art" aria-hidden="true"><div class="home-shape">${icon('home', 72)}</div><div class="floating-chip verified-chip">${icon('check', 16)} ${t('verified')}</div><div class="floating-chip help-chip">${icon('calendar', 16)} Easy booking</div></div></section><section class="content-section"><div class="section-heading"><div><p class="eyebrow">Find the right help</p><h2>${t('browse')}</h2></div></div><div class="category-row">${categories.map(c => `<button class="category ${state.category === c.id ? 'selected' : ''}" data-category="${c.id}"><span>${icon(c.icon, 22)}</span>${c.name}</button>`).join('')}</div></section><section class="content-section services-section"><div class="section-heading"><div><p class="eyebrow">Local & verified</p><h2>${t('popular')}</h2></div><span class="service-count">${visible.length} services</span></div><div class="service-grid">${visible.length ? visible.map(serviceCard).join('') : `<div class="empty-state">${t('noResults')}</div>`}</div></section>`);
}

function servicePage(id) {
  const service = getService(id); if (!service) return notFound(); const provider = getProvider(service.providerId);
  return layout(`<div class="page-shell"><button class="back-link" data-route="/">← ${t('back')}</button><div class="detail-layout"><section><div class="service-detail-icon">${icon(service.category, 38)}</div><p class="eyebrow">${categories.find(c => c.id === service.category).name}</p><h1>${service.title}</h1><p class="lead">${service.description}</p><div class="info-row"><span>${icon('clock', 20)} ${service.duration}</span><span class="verified">${icon('check', 16)} ${t('verified')}</span></div><h2>${t('details')}</h2><p class="body-copy">A cooperative skilled worker will visit at your preferred time to assess and complete the work. You can add a useful note while making your request.</p><div class="tag-row">${service.tags.map(tag => `<span>${tag}</span>`).join('')}</div></section><aside class="booking-panel"><p class="eyebrow">${t('provider')}</p>${providerCard(provider, true)}<p class="availability"><span></span>${provider.available}</p><button class="primary-button full" data-route="/booking/${service.id}">${t('book')} ${icon('arrow', 18)}</button></aside></div></div>`);
}

function providerPage(id) {
  const provider = getProvider(id); if (!provider) return notFound(); const service = services.find(s => s.providerId === id);
  return layout(`<div class="page-shell"><button class="back-link" data-route="/service/${service.id}">← ${t('back')}</button><div class="profile-header"><div class="avatar large">${provider.initials}</div><div><p class="eyebrow">${provider.skill}</p><h1>${provider.name} <span class="verified">${icon('check', 18)}</span></h1><p>${provider.experience} · ★ ${provider.rating} (${provider.reviews})</p><p class="availability"><span></span>${provider.available}</p></div></div><div class="profile-layout"><section><h2>${t('about')} ${provider.name}</h2><p class="body-copy">${provider.bio}</p><h2>${t('offers')}</h2><ul class="offer-list">${provider.services.map(x => `<li>${icon('check', 18)} ${x}</li>`).join('')}</ul></section><aside class="booking-panel"><p class="eyebrow">${t('bookingFor')}</p><h3>${service.title}</h3><p>${service.duration}</p><button class="primary-button full" data-route="/booking/${service.id}">${t('book')} ${icon('arrow', 18)}</button></aside></div></div>`);
}

function bookingPage(id) {
  const service = getService(id); if (!service) return notFound(); const provider = getProvider(service.providerId); const today = new Date().toISOString().split('T')[0];
  return layout(`<div class="page-shell narrow"><button class="back-link" data-route="/service/${id}">← ${t('back')}</button><p class="eyebrow">${t('booking')}</p><h1>${t('bookingFor')} ${service.title}</h1><div class="booking-summary">${providerCard(provider, true)}</div><form id="booking-form" class="booking-form"><label>${t('selectDate')}<div class="input-wrap">${icon('calendar', 19)}<input name="date" type="date" min="${today}" required></div></label><label>${t('selectTime')}<div class="input-wrap">${icon('clock', 19)}<select name="time" required><option value="">Select a time</option><option>09:00 – 11:00</option><option>11:00 – 13:00</option><option>14:00 – 16:00</option><option>16:00 – 18:00</option></select></div></label><label>${t('note')}<textarea name="note" placeholder="${t('notePlaceholder')}"></textarea></label><button class="primary-button full" type="submit">${t('request')} ${icon('arrow', 18)}</button></form></div>`);
}

function confirmation() { const booking = state.booking; if (!booking) return home(); const { service, provider, date, time } = booking; return layout(`<div class="confirmation page-shell narrow"><div class="confirmation-mark">${icon('check', 36)}</div><p class="eyebrow">${t('status')}</p><h1>${t('confirmedTitle')}</h1><p class="lead">${t('confirmedText')}</p><div class="confirmation-card"><div><span>${t('bookingFor')}</span><strong>${service.title}</strong></div><div><span>${t('provider')}</span><strong>${provider.name}</strong></div><div><span>${t('selectDate')} & time</span><strong>${new Date(date + 'T00:00:00').toLocaleDateString(state.language === 'hi' ? 'hi-IN' : 'en-IN', { day: 'numeric', month: 'long', year: 'numeric' })} · ${time}</strong></div><div><span>${t('status')}</span><strong class="status-pill">${t('pending')}</strong></div><div><span>${t('reference')}</span><strong>${booking.reference}</strong></div></div><button class="primary-button" data-route="/">${t('returnHome')} ${icon('arrow', 18)}</button></div>`); }
function notFound() { return layout(`<div class="page-shell narrow empty-page"><h1>Page not found</h1><button class="primary-button" data-route="/">${t('returnHome')}</button></div>`); }

function render() { const parts = route().split('/').filter(Boolean); let view = home(); if (parts[0] === 'service') view = servicePage(parts[1]); if (parts[0] === 'provider') view = providerPage(parts[1]); if (parts[0] === 'booking') view = bookingPage(parts[1]); if (parts[0] === 'confirmation') view = confirmation(); app.innerHTML = view; bind(); }
function bind() { document.querySelector('#language')?.addEventListener('change', (e) => { state.language = e.target.value; localStorage.setItem('gigs-language', state.language); render(); }); document.querySelectorAll('[data-route]').forEach(el => el.addEventListener('click', () => navigate(el.dataset.route))); document.querySelectorAll('[data-category]').forEach(el => el.addEventListener('click', () => { state.category = el.dataset.category; render(); })); document.querySelector('#service-search')?.addEventListener('input', (e) => { state.query = e.target.value; render(); document.querySelector('#service-search')?.focus(); }); document.querySelector('#booking-form')?.addEventListener('submit', (e) => { e.preventDefault(); const form = new FormData(e.target); const service = getService(route().split('/').pop()); state.booking = { service, provider: getProvider(service.providerId), date: form.get('date'), time: form.get('time'), reference: `GIG-${Math.floor(100000 + Math.random() * 900000)}` }; navigate('/confirmation'); }); }
window.addEventListener('hashchange', render); render();
