import { categories, services, getProvider, getService } from './data/services.js';
import { copy } from './data/translations.js';
import { icon } from './components/icons.js';

const app = document.querySelector('#app');
const state = { language: localStorage.getItem('gigs-language') || 'en', role: localStorage.getItem('gigs-role') || null, entryRole: null, entryLoading: false, query: '', category: 'all', booking: null };
const t = (key) => copy[state.language][key] || copy.en[key] || key;
const route = () => location.hash.slice(1) || '/';
const navigate = (path) => { location.hash = path; window.scrollTo({ top: 0, behavior: 'smooth' }); };
const safe = (value) => String(value).replace(/[&<>'"]/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#039;', '"':'&quot;' }[c]));

const providerCard = (p, compact = false) => `<article class="provider-card ${compact ? 'compact' : ''}"><div class="avatar">${p.initials}</div><div class="provider-copy"><div class="provider-name-line"><strong>${p.name}</strong><span class="verified" title="${t('verified')}">${icon('check',14)}</span></div><span>${p.skill}</span><div class="provider-meta"><span>★ ${p.rating} (${p.reviews})</span><span>${p.experience}</span></div></div>${compact ? '' : `<button class="text-button" data-route="/provider/${p.id}">${t('viewProfile')} ${icon('chevron',16)}</button>`}</article>`;
const serviceCard = (s) => { const p = getProvider(s.providerId); return `<article class="service-card"><div class="service-icon">${icon(s.category)}</div><div class="service-card-content"><p class="eyebrow">${categories.find(c => c.id === s.category).name}</p><h3>${s.title}</h3><p>${s.description}</p><div class="card-footer"><span>${p.name}</span><button class="round-button" aria-label="View ${s.title}" data-route="/service/${s.id}">${icon('arrow',18)}</button></div></div></article>`; };
const header = () => `<header class="site-header"><a href="#/home" class="brand" aria-label="GIGS home"><span class="brand-mark">G</span><span>GIGS</span></a><nav aria-label="Main navigation"><a href="#/home" class="active">${t('navHome')}</a></nav><div class="header-actions"><label class="language-select"><span class="sr-only">${t('language')}</span><select id="language" aria-label="${t('language')}"><option value="en" ${state.language === 'en' ? 'selected' : ''}>English</option><option value="hi" ${state.language === 'hi' ? 'selected' : ''}>हिन्दी</option></select></label><button class="logout-button" id="logout" type="button">Log out</button></div></header>`;
const layout = (content) => `${header()}<main class="app-main">${content}</main><footer><div class="footer-brand"><span class="brand-mark">G</span> GIGS</div><span>Cooperative services, close to home.</span></footer>`;

function entry() { return `<main class="entry-screen"><div class="entry-glow glow-one"></div><div class="entry-glow glow-two"></div><section class="entry-panel" aria-labelledby="entry-title"><a href="#/" class="brand entry-brand"><span class="brand-mark">G</span><span>GIGS</span></a><div class="entry-intro"><p class="eyebrow">Welcome to GIGS</p><h1 id="entry-title">Cooperative services,<br>made simple.</h1><p>Choose how you would like to enter the GIGS demo.</p></div><div class="role-grid"><article class="role-card customer-role"><div class="role-icon">${icon('home',31)}</div><p class="eyebrow">I need a service</p><h2>Customer</h2><p>Find trusted workers and book services easily.</p><button class="primary-button full role-button" data-role="customer">Continue as Customer ${icon('arrow',18)}</button></article><article class="role-card worker-role"><div class="role-icon">${icon('carpentry',31)}</div><p class="eyebrow">I offer my skills</p><h2>Worker</h2><p>Offer your skills and manage service requests.</p><button class="primary-button full role-button" data-role="worker">Continue as Worker ${icon('arrow',18)}</button></article></div><p class="demo-note">Demo experience — no account needed.</p></section></main>`; }
function entryMinimal() { return `<main class="entry-screen"><div class="login-background" aria-hidden="true"></div><div class="login-choice" ${state.entryRole ? 'aria-hidden="true"' : ''}><section class="login-box"><h2>USER LOGIN</h2><button class="login-block" data-login-role="customer" type="button">LOGIN</button></section><section class="login-box"><h2>WORKER LOGIN</h2><button class="login-block" data-login-role="worker" type="button">LOGIN</button></section></div>${state.entryRole ? `<section class="login-modal" role="dialog" aria-modal="true"><form id="demo-login-form" class="minimal-login-form"><label>Email<input type="email" name="email" autocomplete="email" required autofocus></label><label>Password<input type="password" name="password" autocomplete="current-password" required></label><button type="submit" class="login-submit" ${state.entryLoading ? 'disabled' : ''}>${state.entryLoading ? '<span class="loader" aria-label="Loading"></span>' : 'LOGIN'}</button></form></section>` : ''}</main>`; }
function home() { const visible = services.filter(s => (state.category === 'all' || s.category === state.category) && `${s.title} ${s.description}`.toLowerCase().includes(state.query.toLowerCase())); return layout(`<section class="hero"><div class="hero-content"><p class="eyebrow">${t('heroEyebrow')}</p><h1>${t('heroTitle')}</h1><p class="hero-text">${t('heroText')}</p><div class="search-box">${icon('search',22)}<input id="service-search" value="${safe(state.query)}" placeholder="${t('search')}" aria-label="${t('search')}" /></div></div><div class="hero-art" aria-hidden="true"><div class="home-shape">${icon('home',72)}</div><div class="floating-chip verified-chip">${icon('check',16)} ${t('verified')}</div><div class="floating-chip help-chip">${icon('calendar',16)} Easy booking</div></div></section><section class="content-section"><div class="section-heading"><div><p class="eyebrow">Find the right help</p><h2>${t('browse')}</h2></div></div><div class="category-row">${categories.map(c => `<button class="category ${state.category === c.id ? 'selected' : ''}" data-category="${c.id}"><span>${icon(c.icon,22)}</span>${c.name}</button>`).join('')}</div></section><section class="content-section services-section"><div class="section-heading"><div><p class="eyebrow">Local & verified</p><h2>${t('popular')}</h2></div><span class="service-count">${visible.length} services</span></div><div class="service-grid">${visible.length ? visible.map(serviceCard).join('') : `<div class="empty-state">${t('noResults')}</div>`}</div></section>`); }
function worker() { const jobs=[['Kitchen plumbing repair','Green Park, Block B','Today · 2:00 PM','New request'],['Bathroom fitting check','Lake View Apartments','Tomorrow · 10:00 AM','Upcoming'],['Pipe leak assessment','Community Hall','Friday · 4:00 PM','Upcoming']]; return layout(`<section class="worker-shell"><p class="eyebrow">GIGS worker demo</p><h1>Welcome, Worker</h1><p class="lead">Here are a few service requests waiting for your attention.</p><div class="worker-list">${jobs.map((j,i)=>`<article class="request-card"><div class="request-icon">${icon(i===1?'plumbing':'home',23)}</div><div><span class="request-status ${i===0?'new':''}">${j[3]}</span><h2>${j[0]}</h2><p>${j[1]}</p><span class="request-time">${icon('calendar',15)} ${j[2]}</span></div><button class="request-view" type="button" aria-label="View ${j[0]}">${icon('chevron',20)}</button></article>`).join('')}</div></section>`); }
function servicePage(id) { const s=getService(id); if(!s) return notFound(); const p=getProvider(s.providerId); return layout(`<div class="page-shell"><button class="back-link" data-route="/home">← ${t('back')}</button><div class="detail-layout"><section><div class="service-detail-icon">${icon(s.category,38)}</div><p class="eyebrow">${categories.find(c=>c.id===s.category).name}</p><h1>${s.title}</h1><p class="lead">${s.description}</p><div class="info-row"><span>${icon('clock',20)} ${s.duration}</span><span class="verified">${icon('check',16)} ${t('verified')}</span></div><h2>${t('details')}</h2><p class="body-copy">A cooperative skilled worker will visit at your preferred time to assess and complete the work. You can add a useful note while making your request.</p><div class="tag-row">${s.tags.map(tag=>`<span>${tag}</span>`).join('')}</div></section><aside class="booking-panel"><p class="eyebrow">${t('provider')}</p>${providerCard(p,true)}<p class="availability"><span></span>${p.available}</p><button class="primary-button full" data-route="/booking/${s.id}">${t('book')} ${icon('arrow',18)}</button></aside></div></div>`); }
function providerPage(id) { const p=getProvider(id); if(!p) return notFound(); const s=services.find(x=>x.providerId===id); return layout(`<div class="page-shell"><button class="back-link" data-route="/service/${s.id}">← ${t('back')}</button><div class="profile-header"><div class="avatar large">${p.initials}</div><div><p class="eyebrow">${p.skill}</p><h1>${p.name} <span class="verified">${icon('check',18)}</span></h1><p>${p.experience} · ★ ${p.rating} (${p.reviews})</p><p class="availability"><span></span>${p.available}</p></div></div><div class="profile-layout"><section><h2>${t('about')} ${p.name}</h2><p class="body-copy">${p.bio}</p><h2>${t('offers')}</h2><ul class="offer-list">${p.services.map(x=>`<li>${icon('check',18)} ${x}</li>`).join('')}</ul></section><aside class="booking-panel"><p class="eyebrow">${t('bookingFor')}</p><h3>${s.title}</h3><p>${s.duration}</p><button class="primary-button full" data-route="/booking/${s.id}">${t('book')} ${icon('arrow',18)}</button></aside></div></div>`); }
function bookingPage(id) { const s=getService(id); if(!s) return notFound(); const p=getProvider(s.providerId); const today=new Date().toISOString().split('T')[0]; return layout(`<div class="page-shell narrow"><button class="back-link" data-route="/service/${id}">← ${t('back')}</button><p class="eyebrow">${t('booking')}</p><h1>${t('bookingFor')} ${s.title}</h1><div class="booking-summary">${providerCard(p,true)}</div><form id="booking-form" class="booking-form"><label>${t('selectDate')}<div class="input-wrap">${icon('calendar',19)}<input name="date" type="date" min="${today}" required></div></label><label>${t('selectTime')}<div class="input-wrap">${icon('clock',19)}<select name="time" required><option value="">Select a time</option><option>09:00 – 11:00</option><option>11:00 – 13:00</option><option>14:00 – 16:00</option><option>16:00 – 18:00</option></select></div></label><label>${t('note')}<textarea name="note" placeholder="${t('notePlaceholder')}"></textarea></label><button class="primary-button full" type="submit">${t('request')} ${icon('arrow',18)}</button></form></div>`); }
function confirmation(){const b=state.booking;if(!b)return home();return layout(`<div class="confirmation page-shell narrow"><div class="confirmation-mark">${icon('check',36)}</div><p class="eyebrow">${t('status')}</p><h1>${t('confirmedTitle')}</h1><p class="lead">${t('confirmedText')}</p><div class="confirmation-card"><div><span>${t('bookingFor')}</span><strong>${b.service.title}</strong></div><div><span>${t('provider')}</span><strong>${b.provider.name}</strong></div><div><span>${t('selectDate')} & time</span><strong>${new Date(b.date+'T00:00:00').toLocaleDateString(state.language==='hi'?'hi-IN':'en-IN',{day:'numeric',month:'long',year:'numeric'})} · ${b.time}</strong></div><div><span>${t('status')}</span><strong class="status-pill">${t('pending')}</strong></div><div><span>${t('reference')}</span><strong>${b.reference}</strong></div></div><button class="primary-button" data-route="/home">${t('returnHome')} ${icon('arrow',18)}</button></div>`);}
function notFound(){return layout(`<div class="page-shell narrow empty-page"><h1>Page not found</h1><button class="primary-button" data-route="/home">${t('returnHome')}</button></div>`);}
function render(){const parts=route().split('/').filter(Boolean);if(!state.role){app.innerHTML=entryMinimal();bind();return;}let view=state.role==='worker'?worker():home();if(state.role==='customer'&&parts[0]==='home')view=home();if(state.role==='worker'&&parts[0]==='worker')view=worker();if(state.role==='customer'&&parts[0]==='service')view=servicePage(parts[1]);if(state.role==='customer'&&parts[0]==='provider')view=providerPage(parts[1]);if(state.role==='customer'&&parts[0]==='booking')view=bookingPage(parts[1]);if(state.role==='customer'&&parts[0]==='confirmation')view=confirmation();app.innerHTML=view;bind();}
function bind(){document.querySelector('#language')?.addEventListener('change',e=>{state.language=e.target.value;localStorage.setItem('gigs-language',state.language);render();});document.querySelector('#logout')?.addEventListener('click',()=>{state.role=null;state.booking=null;state.entryRole=null;localStorage.removeItem('gigs-role');navigate('/');});document.querySelectorAll('[data-login-role]').forEach(el=>el.addEventListener('click',()=>{state.entryRole=el.dataset.loginRole;render();}));document.querySelector('#demo-login-form')?.addEventListener('submit',e=>{e.preventDefault();state.entryLoading=true;render();setTimeout(()=>{state.role=state.entryRole;state.entryRole=null;state.entryLoading=false;localStorage.setItem('gigs-role',state.role);navigate(state.role==='customer'?'/home':'/worker');},550);});document.querySelectorAll('[data-route]').forEach(el=>el.addEventListener('click',()=>navigate(el.dataset.route)));document.querySelectorAll('[data-category]').forEach(el=>el.addEventListener('click',()=>{state.category=el.dataset.category;render();}));document.querySelector('#service-search')?.addEventListener('input',e=>{state.query=e.target.value;render();document.querySelector('#service-search')?.focus();});document.querySelector('#booking-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),s=getService(route().split('/').pop());state.booking={service:s,provider:getProvider(s.providerId),date:f.get('date'),time:f.get('time'),reference:`GIG-${Math.floor(100000+Math.random()*900000)}`};navigate('/confirmation');});}
window.addEventListener('hashchange',render);render();
